### PR TITLE
onehost build

### PR DESCRIPTION
**Pull request by wgyt**
solves #8

### CODE REVIEW

**Comment by RedGuy12** [comment]
i tried to work on #1 and then you revert it all in this pr 😢

**Comment by wgyt** [comment]
> i tried to work on #1 and then you revert it all in this pr 😢

I didn't try to revert it, but I started working before you made the commit

**Comment by wgyt** [comment]
I'm fixing the merge conflicts so repl db is included

**Comment by wgyt** [comment]
@RedGuy12 I fixed the merge conflicts so your changes are included.

**Comment by wgyt** [comment]
@RedGuy12 I'm merging this pull request now

**Pull request merged**
